// Auto-generated by a3_teleop_bridge/tools/make_cpp_reference_limits.py
// DO NOT EDIT BY HAND.
//
// Source: /inspire/hdd/global_user/liumengfan-253108110079/wsc-workspace/a3_teleop_ws/a3_teleop_bridge/generated/a3_joint_limits.yaml
// Generated: 2026-09-27T09:37:10+00:00
//
// Joint order is the ENCODER (il) order of A3_REFERENCE_V1.
#pragma once

#include <array>
#include <cstddef>

namespace a3_deploy {

struct A3ReferenceLimits {
  static constexpr std::size_t kJoints = 29;
  const char* const* joint_names;
  std::array<float, kJoints> position_lower;
  std::array<float, kJoints> position_upper;
  std::array<float, kJoints> velocity;
  float position_tolerance;
  float velocity_scale;
};

inline constexpr std::size_t kA3ReferenceJointCount = A3ReferenceLimits::kJoints;
inline const char* const kA3ReferenceJointNames[kA3ReferenceJointCount] = {
    "left_hip_pitch_joint",
    "right_hip_pitch_joint",
    "waist_yaw_joint",
    "left_hip_roll_joint",
    "right_hip_roll_joint",
    "waist_roll_joint",
    "left_hip_yaw_joint",
    "right_hip_yaw_joint",
    "waist_pitch_joint",
    "left_knee_joint",
    "right_knee_joint",
    "left_shoulder_pitch_joint",
    "right_shoulder_pitch_joint",
    "left_ankle_pitch_joint",
    "right_ankle_pitch_joint",
    "left_shoulder_roll_joint",
    "right_shoulder_roll_joint",
    "left_ankle_roll_joint",
    "right_ankle_roll_joint",
    "left_shoulder_yaw_joint",
    "right_shoulder_yaw_joint",
    "left_elbow_joint",
    "right_elbow_joint",
    "left_wrist_roll_joint",
    "right_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "right_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    "right_wrist_yaw_joint",
};

inline constexpr A3ReferenceLimits kA3ReferenceLimits = {
    kA3ReferenceJointNames,
    {{
    -2.51327412f, -2.51327412f, -2.61799388f, -0.523598776f, -1.60570291f,
    -0.34906585f, -2.72271363f, -2.72271363f, -0.488692191f, -0.122173048f,
    -0.122173048f, -2.87979327f, -2.87979327f, -0.907571211f, -0.907571211f,
    -0.0872664626f, -2.61799388f, -0.34906585f, -0.34906585f, -2.7925268f,
    -2.7925268f, -0.959931089f, -0.959931089f, -2.7925268f, -2.7925268f,
    -1.6231562f, -1.6231562f, -1.6231562f, -1.6231562f,
    }},
    {{
    2.93215314f, 2.93215314f, 2.61799388f, 1.60570291f, 0.523598776f,
    0.34906585f, 2.72271363f, 2.72271363f, 0.41887902f, 2.49582083f,
    2.49582083f, 2.87979327f, 2.87979327f, 0.523598776f, 0.523598776f,
    2.61799388f, 0.0872664626f, 0.34906585f, 0.34906585f, 2.7925268f,
    2.7925268f, 1.74532925f, 1.74532925f, 2.7925268f, 2.7925268f,
    1.6231562f, 1.6231562f, 1.6231562f, 1.6231562f,
    }},
    {{
    12.0427718f, 12.0427718f, 12.0427718f, 12.0427718f, 12.0427718f,
    22.7f, 12.0427718f, 12.0427718f, 9.24785f, 14.6607657f,
    14.6607657f, 13.6135682f, 13.6135682f, 10.8f, 10.8f,
    13.6135682f, 13.6135682f, 19.37f, 19.37f, 15.7079633f,
    15.7079633f, 15.7079633f, 15.7079633f, 15.7079633f, 15.7079633f,
    12.7758101f, 12.7758101f, 12.7758101f, 12.7758101f,
    }},
    0.02f,
    1.05f,
};

}  // namespace a3_deploy
