// Bridge from A3_REFERENCE_V1 to the A3 teleop command channel (plan sections 59/60).
//
// The official A3 runtime already consumes a teleop reference through
// `A3TeleopReference` (see `a3_teleop_reference.hpp`), fed by
// `/ta/whole_body_command`.  This component produces exactly the field groups that
// channel carries, from the windows our Orin publishes:
//
//     A3ReferenceWindow (10 x 29, encoder/il order)
//         -> A3WholeBodyCommandFields (waist/arm/leg groups, policy order)
//         -> /ta/whole_body_command
//
// `ConvertTaWholeBodyCommand` in `a3_teleop_reference.cpp` documents the policy
// view order this file targets:
//
//     waist[0..2], left arm[3..9], right arm[10..16],
//     left leg[17..22], right leg[23..28]
//
// The permutation between that order and the wire order is generated by
// `a3_teleop_bridge/tools/make_cpp_joint_order.py` -- never index by hand.
//
// The only thing that needs the AimRT types is the final `publish()` call; that is
// intentionally left to the robot-side wiring (see docs/A3_ONBOARD.md section 2).
#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <vector>

#include "a3_deploy/a3_reference_limits.hpp"
#include "a3_deploy/a3_reference_stream.hpp"
#include "a3_deploy/a3_teleop_joint_order.hpp"

namespace a3_deploy {

// Field groups of /ta/whole_body_command, in the layout its converter expects.
// Velocities use the protocol layout: leg(12) + waist(3) + head(1) + arm(14).
struct A3WholeBodyCommandFields {
  std::int64_t stamp_ns = 0;
  std::array<double, 4> pelvis_quat_wxyz{1.0, 0.0, 0.0, 0.0};
  std::array<double, 3> pelvis_position_m{};  // world frame, x-forward y-left z-up
  std::array<double, 12> leg_angles_rad{};   // [0..5] left leg, [6..11] right leg
  std::array<double, 3> waist_angles_rad{};  // yaw, roll, pitch
  std::array<double, 14> arm_angles_rad{};   // [0..6] left arm, [7..13] right arm
  std::array<double, 2> head_angles_rad{};   // A3_REFERENCE_V1 carries no head data
  bool has_head_command = false;
  std::array<double, 30> velocities_rad_s{};
  bool has_velocities = false;
};

// Convert one frame of a reference window into the channel fields.
//
// `stamp_ns` is the timestamp to publish with (already mapped onto the robot
// clock).  Joints are validated against the encoder-order limits in
// `kA3ReferenceLimits`; head targets stay absent because the wire protocol has
// none (`has_head_command == false` lets the runtime keep its own head target).
bool BuildWholeBodyCommandFromReference(const A3ReferenceWindow& window,
                                        int frame_index,
                                        std::int64_t stamp_ns,
                                        A3WholeBodyCommandFields* out,
                                        std::string* error = nullptr);

struct A3TeleopCommandPumpOptions {
  // Align with the official frame-age watchdog (a3_runtime_config.yaml).
  double stale_after_ms = 50.0;
  // A 20 Hz window covers 200 ms of motion, so emitting every frame keeps the
  // runtime's 50 Hz delay buffer dense.  With false only frame 0 is emitted and
  // the runtime falls back to its own future_frame_skip extrapolation.
  bool emit_all_window_frames = true;
  // Reject a teleport between consecutive emitted ticks.
  double max_joint_step_rad = 0.5;
  // Reject (do not clamp) joints outside the encoder-order limits.
  bool enforce_limits = true;
};

struct A3TeleopCommandPumpStats {
  std::uint64_t windows_accepted = 0;
  std::uint64_t windows_rejected = 0;
  std::uint64_t frames_emitted = 0;
  std::uint64_t frames_skipped_stale_stamp = 0;
  std::uint64_t rejected_nan = 0;
  std::uint64_t rejected_limits = 0;
  std::uint64_t rejected_step = 0;
  std::string last_error;
};

// Turns a stream of reference windows into a monotonic stream of commands.
//
// Timestamps: the first window calibrates a constant offset between the publisher
// clock and the local clock (`receive_ns - window.timestamp_ns`); every emitted
// frame is stamped `window.timestamp_ns + frame * dt + offset`.  Both hosts are
// expected to be NTP/chrony synchronised, which this offset absorbs.
class A3TeleopCommandPump {
 public:
  explicit A3TeleopCommandPump(A3TeleopCommandPumpOptions options = {});

  void Configure(const A3TeleopCommandPumpOptions& options);
  void Reset();

  // Feed one decoded window.  Emitted commands are appended to `out` (cleared
  // first).  Returns false only when the window was rejected outright.
  bool PushWindow(const A3ReferenceWindow& window,
                  std::int64_t receive_ns,
                  std::vector<A3WholeBodyCommandFields>* out,
                  std::string* error = nullptr);

  // True when the caller must stop publishing (the runtime then holds its last
  // command and safe-halts on its own watchdog).
  bool ShouldHold(std::int64_t now_ns) const;

  std::int64_t ClockOffsetNs() const { return clock_offset_ns_; }
  std::int64_t LastPushNs() const { return last_push_ns_; }
  std::int64_t LastReceiveNs() const { return last_receive_ns_; }
  std::uint64_t LastSeq() const { return last_seq_; }
  const A3TeleopCommandPumpStats& Stats() const { return stats_; }

 private:
  A3TeleopCommandPumpOptions options_{};
  A3TeleopCommandPumpStats stats_{};
  bool clock_calibrated_ = false;
  std::int64_t clock_offset_ns_ = 0;
  std::int64_t last_push_ns_ = 0;
  std::int64_t last_receive_ns_ = 0;
  std::uint64_t last_seq_ = 0;
  std::array<double, kA3ReferenceJointCount> last_policy_q_{};
  bool have_last_q_ = false;
};

}  // namespace a3_deploy
