// Auto-generated by a3_teleop_bridge/tools/make_cpp_joint_order.py
// DO NOT EDIT BY HAND.
//
// Source: /inspire/hdd/global_user/liumengfan-253108110079/wsc-workspace/a3_teleop_ws/a3_teleop_bridge/generated/a3_contract.json (sha256 b8b2c6b29eace6d6cb7d1d18f15794473382f82fc4ee77f9348306fc6f0815e2)
// Generated: 2026-09-28T02:22:12+00:00
//
// Two distinct 29-joint orders are in play on the robot:
//   * `kA3IlJointNames`      -- the order of A3_REFERENCE_V1 (encoder / IsaacLab)
//   * `kA3PolicyJointNames`  -- the order of /ta/whole_body_command and of the
//                               A3TeleopFrame that A3TeleopReference consumes
//                               (waist[0..2], left arm[3..9], right arm[10..16],
//                                left leg[17..22], right leg[23..28])
//
// The permutations below are the only sanctioned way to cross between them.
#pragma once

#include <array>
#include <cstddef>

namespace a3_deploy {

inline constexpr std::size_t kA3TeleopJointCount = 29;

// Policy view order (what the runtime tokenizer expects).
inline const char* const kA3PolicyJointNames[kA3TeleopJointCount] = {
    "waist_yaw_joint",
    "waist_roll_joint",
    "waist_pitch_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_roll_joint",
    "right_wrist_pitch_joint",
    "right_wrist_yaw_joint",
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
};

// Encoder (il) order (what A3_REFERENCE_V1 carries).
inline const char* const kA3IlJointNames[kA3TeleopJointCount] = {
    "left_hip_pitch_joint",
    "right_hip_pitch_joint",
    "waist_yaw_joint",
    "left_hip_roll_joint",
    "right_hip_roll_joint",
    "waist_roll_joint",
    "left_hip_yaw_joint",
    "right_hip_yaw_joint",
    "waist_pitch_joint",
    "left_knee_joint",
    "right_knee_joint",
    "left_shoulder_pitch_joint",
    "right_shoulder_pitch_joint",
    "left_ankle_pitch_joint",
    "right_ankle_pitch_joint",
    "left_shoulder_roll_joint",
    "right_shoulder_roll_joint",
    "left_ankle_roll_joint",
    "right_ankle_roll_joint",
    "left_shoulder_yaw_joint",
    "right_shoulder_yaw_joint",
    "left_elbow_joint",
    "right_elbow_joint",
    "left_wrist_roll_joint",
    "right_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "right_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    "right_wrist_yaw_joint",
};

// kA3PolicyToIlIndex[policy_index] = index inside the wire payload.
inline constexpr std::array<int, kA3TeleopJointCount> kA3PolicyToIlIndex = {2, 5, 8, 11, 15, 19, 21, 23, 25, 27, 12, 16, 20, 22, 24, 26, 28, 0, 3, 6, 9, 13, 17, 1, 4, 7, 10, 14, 18};

// kA3IlToPolicyIndex[wire_index] = index inside the policy view.
inline constexpr std::array<int, kA3TeleopJointCount> kA3IlToPolicyIndex = {17, 23, 0, 18, 24, 1, 19, 25, 2, 20, 26, 3, 10, 21, 27, 4, 11, 22, 28, 5, 12, 6, 13, 7, 14, 8, 15, 9, 16};

}  // namespace a3_deploy
